from enum import Enum

class ResponseCodes(str, Enum):
    SUCCESS = "SUCCESS"
    ERROR = "ERROR"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
    RESTOCK_TOKEN_SUCCESS = "RESTOCK_TOKEN_SUCCESS"
    LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
    
    GET_ACCOUNT_BY_ID_SUCCESS = "GET_ACCOUNT_BY_ID_SUCCESS"

    GET_MEDIA_BY_ID_SUCCESS = "GET_MEDIA_BY_ID_SUCCESS"
    STORAGE_MEDIA_SUCCESS = "STORAGE_MEDIA_SUCCESS"

    GET_MESSAGE_BY_ID_SUCCESS = "GET_MESSAGE_BY_ID_SUCCESS"
    GET_LAST_CONVERSATION_MESSAGE_SUCCESS = "GET_LAST_CONVERSATION_MESSAGE_SUCCESS"

    GET_CONVERSATION_BY_ID_SUCCESS = "GET_CONVERSATION_BY_ID_SUCCESS"

    GET_PROFILE_BY_ID_SUCCESS = "GET_PROFILE_BY_ID_SUCCESS"
    SEARCH_PROFILE_SUCCESS = "SEARCH_PROFILE_SUCCESS"
    GET_ALL_PROFILES_SUCCESS = "GET_ALL_PROFILES_SUCCESS"

    UPDATE_RELATION_SUCCESS = "UPDATE_RELATION_SUCCESS"
    CREATE_RELATION_SUCCESS = "CREATE_RELATION_SUCCESS"
    GET_ALL_RELATIONS_SUCCESS = "GET_ALL_RELATIONS_SUCCESS"
    SEARCH_RELATION_SUCCESS = "SEARCH_RELATION_SUCCESS"
    GET_RELATION_BY_ID_SUCCESS = "GET_RELATION_BY_ID_SUCCESS"
    
    GET_PROFILE_CONVERSATION_SUCCESS = "GET_PROFILE_CONVERSATION_SUCCESS"

    def __str__(self):
        return self.value